application: courserecommendation
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on

inbound_services:
- warmup

handlers:
- url: /_ah/queue/deferred
  script: djangoappengine/deferred/handler.py
  login: admin

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'


- url: /media
  static_dir: media/
  expiration: '365d'

- url: /.*
  script: djangoappengine/main/main.py

- url: /update_rating_alg/
  script: djangoappengine/main/main.py
  login: admin
